### PR TITLE
[DO-2455] Shadow when scroll on table

### PR DESCRIPTION
**Pull request by Iva-khar**

### CODE REVIEW

**Review by roman-tiukh — CHANGES_REQUESTED** [review]
I have a lot of questions and suggestions, need a call.

**Review by roman-tiukh — CHANGES_REQUESTED** [review]
you delete package-lock.json

**Comment by Iva-khar** [comment]
> you delete package-lock.json

no...

https://github.com/3v-workspace/DataOcean/pull/201/files#diff-053150b640a7ce75eff69d1a22cae7f0f94ad64ce9a855db544dda0929316519

38 additions, 24,241 deletions not shown because the diff is too large. Please use a local Git client to view these changes.

**Review by roman-tiukh — CHANGES_REQUESTED** [review]
package-lock.json
there shouldn't be that many deletions

**Comment by Iva-khar** [comment]
> package-lock.json
> there shouldn't be that many deletions

fixed

**Review by roman-tiukh — APPROVED** [review]

**Pull request merged**
