### PR TITLE
[DO-914]

### PR DESCRIPTION
**Pull request by Andrii17s**
Closing option added

### CODE REVIEW

**Comment by Andrii17s** [comment]
@roman-tiukh

**Review by roman-tiukh — CHANGES_REQUESTED** [review]
According to the conditions, all modal windows need to be updated

**Review by roman-tiukh — CHANGES_REQUESTED** [review]
what about other modals?

**Review by roman-tiukh — CHANGES_REQUESTED** [review]
no need to add 2 different tasks to one PR

**Review by roman-tiukh — APPROVED** [review]

**Pull request merged**
